[add] 認証の追加, テスト用パスの追加
fung-hackathon/flyme-backend pull request #13
Opened 2022-12-13 12:31 UTC by TadaTeruki

`/login`のみを実装するつもりでしたが、それだとテスト面の様々な部分で都合が悪いため、認証の仕組みとテスト用のパスも同時に書くことにしました

### テストについて

```
$ curl -X 'GET' \
  'http://localhost:8080/auth/ping' \
  -H 'accept: text/plain' \
  -H 'Authorization: Bearer %/login後に受け取ったトークン%'
```

2022-12-13 14:00 UTC, jugesuke requested changes
ライブラリのバージョンが古いから直したほうがいいかもしれん

2022-12-14 04:17 UTC, TadaTeruki commented on app/packages/auth/auth.go
> +	"github.com/golang-jwt/jwt"
ありがとう

2022-12-14 06:49 UTC, jugesuke reviewed
LGTM

2022-12-14 06:50 UTC, jugesuke approved these changes

2022-12-14 06:50 UTC, merged